APPLICATION_ID: sqlaudit
service_description:
  name: EdgeService
  version: 0.0.1
servicecomb:
  service:
    registry:
      address: http://127.0.0.1:30100
  rest:
    address: 0.0.0.0:8100

  http:
    dispatcher:
      edge:
        http:
          enabled: true
          mappings:
            parsing:
              prefixSegmentCount: 0
              path: "/.*"
              microserviceName: ParsingService
              versionRule: 0.0.0+
